<?php
defined('WEKIT_VERSION') or exit(403);
Wind::import('ADMIN:library.AdminBaseController');

/**
 * 后台访问入口
 *
 * generated by phpwind.com
 */
class ManageController extends AdminBaseController {
	
	public function run() {
		$config = Wekit::C()->getValues('site');
		$this->setOutput($config, 'config');
	}
	
	public function dorunAction() {
		list($ifopen, $readifopen, $spaceifopen) = $this->getInput(array('ifopen', 'readifopen', 'spaceifopen'), 'post');

		$config = new PwConfigSet('site');
		$config->set('app.dongta.ifopen', intval($ifopen))
			->set('app.dongta.read.ifopen', intval($readifopen))
			->set('app.dongta.space.ifopen', intval($spaceifopen))
			->flush();

		$this->showMessage('operate.success');
	}
}
?>