<?php
defined('WEKIT_VERSION') or exit(403);
Wind::import('EXT:majia.service.srv.App_Majia_MajiaBandingBp');
/**
 * 前台入口
 *
 * generated by phpwind.com
 */
class IndexController extends PwBaseController {
	
	/* (non-PHPdoc)
	 * @see PwBaseController::beforeAction()
	 */
	public function beforeAction($handlerAdapter) {
		parent::beforeAction($handlerAdapter);
		if (!$this->loginUser->isExists()) {
			$this->showError('login.not', 'u/login/run');
		}
		if (!Wekit::C('app_majia', 'isopen')) $this->showError('马甲绑定没有开启');
	}
	
	/* (non-PHPdoc)
	 * @see WindController::run()
	 */
	public function run() {
		$bp = new App_Majia_MajiaBandingBp($this->loginUser);
		$list = $bp->doGetBanded();
		$num = intval(Wekit::C('app_majia', 'band.max.num'));
		$this->setOutput($list, 'list');
		$this->setOutput($num, 'num');
		$this->setOutput($num - count($list), 'hasNum');
		$this->setTemplate('pop_run');
	}
	
	/**
	 * 解除绑定
	 */
	public function unbandAction() {
		$uid = $this->getInput('uid');
		$bp = new App_Majia_MajiaBandingBp($this->loginUser);
		$result = $bp->doUnBanding($uid);
		if ($result instanceof PwError) {
			$this->showError($result->getError());
		}
		$this->showMessage('解绑成功');
	}
		
	/**
	 * 执行绑定弹窗
	 */
	public function bandAction() {
		if (2 == $this->getInput('step', 'post')) {
			$bp = new App_Majia_MajiaBandingBp($this->loginUser);
			$result = $bp->doBanding($this->getInput('username', 'post'), $this->getInput('password', 'post'));
			if ($result instanceof PwError) {
				$this->showError($result->getError());
			}
			$this->showMessage('绑定成功');
		}
		$this->showError('operator.fail');
	}
	
	/**
	 * 执行重新绑定
	 */
	public function reBandAction() {
		if (2 == $this->getInput('step', 'post')) {
			$bp = new App_Majia_MajiaBandingBp($this->loginUser);
			$result = $bp->doReBanding($this->getInput('username', 'post'), $this->getInput('password', 'post'));
			if ($result instanceof PwError) {
				$this->showError($result->getError());
			}
			$this->showMessage('重新绑定成功');
		} else {
			$uid = $this->getInput('uid', 'get');
			if (!$uid) $this->showError('请选择需要重新绑定的帐号');
			$username = Wekit::load('SRV:user.PwUser')->getUserByUid($uid);
			if (!$username) {
				$this->showError('请选择需要重新绑定的帐号');
			}
			$this->setOutput($username, 'info');
		}
		$this->setTemplate('pop_reband');
	}
	
	/**
	 * 马甲切换
	 */
	public function changeAction() {
		$uid = $this->getInput('uid', 'get');
		$bp = new App_Majia_MajiaBandingBp($this->loginUser);
		$result = $bp->doChangeAccount($uid);
		if ($result instanceof PwError) {
			$error = $result->getError();
			if ($error == '密码失效，请重新绑定') {
				$this->addMessage(array('reband' => WindUrlHelper::createUrl('app/majia/my/reBand?uid=' . $uid)), 'data');
				$this->showError('密码失效，需要重新绑定');
			} else {
				$this->showError($error);
			}
		}
		Wekit::load('SRV:user.srv.PwLoginService')->setLoginCookie(new PwUserBo($uid), $this->getRequest()->getClientIp());
		WindidApi::api('user')->synLogin($uid);
		$this->showMessage('切换成功');
	}
}
?>