<?php
defined('WEKIT_VERSION') or exit(403);
Wind::import('ADMIN:library.AdminBaseController');
/**
 * 后台访问入口
 *
 * generated by phpwind.com
 */
class ManageController extends AdminBaseController {

	public function beforeAction($handlerAdapter) {
		parent::beforeAction($handlerAdapter);
		// TODO do something before all the action
	}

	public function run() {
		$config = Wekit::C('site');
		$this->setOutput(
			array(
				'isopen' => $config['app.signature.isopen'], 
				'money' => $config['app.signature.money'], 
				'moneytype' => $config['app.signature.moneytype'], 
				'groups' => $config['app.signature.groups']));
		Wind::import('SRV:credit.bo.PwCreditBo');
		/* @var $pwCreditBo PwCreditBo */
		$pwCreditBo = PwCreditBo::getInstance();
		$this->setOutput($pwCreditBo->cType, 'credit');
		
		$userGroup = Wekit::load('usergroup.PwUserGroups');
		$groups = $userGroup->getAllGroups();
		$groupTypes = $userGroup->getTypeNames();
		$this->setOutput($groups, 'usergroups');
		$this->setOutput($groupTypes, 'groupTypes');
	}

	public function doRunAction() {
		list($type, $money, $isopen, $groups) = $this->getInput(array('moneytype', 'money', 'isopen', 'groups'), 
			'post');
		$bo = new PwConfigSet('site');
		$bo->set('app.signature.moneytype', $type)->set('app.signature.money', intval($money))->set(
			'app.signature.isopen', $isopen)->set('app.signature.groups', $groups ? ',' . implode(',', $groups) . ',' : '')->flush();
		$this->showMessage('success');
	}
}

?>